export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';

export const ADD_OUTFIT = 'ADD_OUTFIT';
export const DELETE_OUTFIT = 'DELETE_OUTFIT';
export const EDIT_OUTFIT = 'EDIT_OUTFIT';

export const SET_TOP_TYPE_FILTER = 'SET_TOP_TYPE_FILTER';
export const TopTypeFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_SEPARATES: 'SHOW_SEPARATES',
	SHOW_DRESSES: 'SHOW_DRESSES'
};

export const SET_BOTTOM_TYPE_FILTER = 'SET_BOTTOM_TYPE_FILTER';
export const BottomTypeFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_CAPRIS: 'SHOW_CAPRIS',
	SHOW_LEGGINGS: 'SHOW_LEGGINGS',
	SHOW_PANTS: 'SHOW_PANTS',
	SHOW_SHORTS: 'SHOW_SHORTS',
	SHOW_SKIRTS: 'SHOW_SKIRTS'
};

export const SET_SHOE_TYPE_FILTER = 'SET_SHOE_TYPE_FILTER';
export const ShoeTypeFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_BOOTS: 'SHOW_BOOTS',
	SHOW_FLATS: 'SHOW_FLATS',
	SHOW_HEELS: 'SHOW_HEELS',
	SHOW_SANDALS: 'SHOW_SANDALS'
};

export const SET_COAT_TYPE_FILTER = 'SET_COAT_TYPE_FILTER';
export const CoatTypeFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_INSULATED: 'SHOW_INSULATED',
	SHOW_LIGHT: 'SHOW_LIGHT',
	SHOW_RAINWEAR: 'SHOW_RAINWEAR'
};

export const SET_ACCESSORY_TYPE_FILTER = 'SET_ACCESSORY_TYPE_FILTER';
export const AccessoryTypeFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_BAG: 'SHOW_BAG',
	SHOW_JEWELRY: 'SHOW_JEWELRY',
	SHOW_HAT: 'SHOW_HAT'
};

export const SET_COLOR_FILTER = 'SET_COLOR_FILTER';
export const ColorFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_BLACK: 'SHOW_BLACK',
	SHOW_BROWN: 'SHOW_BROWN',
	SHOW_RED: 'SHOW_RED',
	SHOW_BLUE: 'SHOW_BLUE',
	SHOW_PURPLE: 'SHOW_PURPLE',
	SHOW_PINK: 'SHOW_PINK',
	SHOW_ORANGE: 'SHOW_ORANGE',
	SHOW_GREEN: 'SHOW_GREEN',
	SHOW_GREY: 'SHOW_GREY',
	SHOW_YELLOW: 'SHOW_YELLOW',
	SHOW_WHITE: 'SHOW_WHITE',
	SHOW_BEIGE: 'SHOW_BEIGE',
	SHOW_GOLD: 'SHOW_GOLD',
	SHOW_SILVER: 'SHOW_SILVER',
};

export const SET_PATTERN_FILTER = 'SET_PATTERN_FILTER';
export const PatternFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_SOLID: 'SHOW_SOLID',
	SHOW_SIMPLE: 'SHOW_SIMPLE',
	SHOW_BUSY: 'SHOW_BUSY'
};

export const SET_OCCASION_FILTER = 'SET_OCCASION_FILTER';
export const OccasionFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_CASUAL: 'SHOW_CASUAL',
	SHOW_BUSINESS_CASUAL: 'SHOW_BUSINESS_CASUAL',
	SHOW_BUSINESS: 'SHOW_BUSINESS',
	SHOW_BUSINESS_FORMAL: 'SHOW_BUSINESS_FORMAL',
	SHOW_FORMAL: 'SHOW_FORMAL'
};

export const SET_SLEEVELENGTH_FILTER = 'SET_SLEEVELENGTH_FILTER';
export const SleeveLengthFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_SLEEVELESS: 'SHOW_SLEEVELESS',
	SHOW_SHORT: 'SHOW_SHORT',
	SHOW_THREE_QUARTERS: 'SHOW_THREE_QUARTERS',
	SHOW_LONG: 'SHOW_LONG'
};